# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      MONGO_URL: ${{ secrets.MONGO_URL }}
      TZ: ${{ secrets.TZ }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Deploy using ssh
          uses: appleboy/ssh-action@master
          with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.PRIVATE_KEY }}
           port: 22
           envs: PORT,MONGO_URL,TZ,AWS_BUCKET_NAME,AWS_ACCESS_KEY,AWS_SECRET_KEY
           script: |
             cd /home/apps/chat_server
             sudo touch .env
             sudo chmod 777 .env
             sudo echo PORT=$PORT >> .env
             sudo echo MONGO_URL=$MONGO_URL >> .env
             sudo echo TZ=$TZ >> .env
             sudo echo AWS_BUCKET_NAME=$AWS_BUCKET_NAME >> .env
             sudo echo AWS_BUCKET_REGION='' >> .env
             sudo echo AWS_ACCESS_KEY=$AWS_ACCESS_KEY >> .env
             sudo echo AWS_SECRET_KEY=$AWS_SECRET_KEY >> .env
             sudo git pull origin main
             sudo git status
             sudo npm install --only=prod
             sudo pm2 restart chat_server_node
